export const ordersData = [
 {
  no: '001',
  productName: 'Haier Thermocool',
  customer: 'Justin Bieber',
  dateCreated: '20-03-2024',
  location: 'Lagos, Nigeria',
  status: 'Ongoing',
 },
 {
  no: '002',
  productName: 'Samsung Fridge',
  customer: 'Ariana Grande',
  dateCreated: '21-03-2024',
  location: 'Abuja, Nigeria',
  status: 'Ongoing',
 },
 {
  no: '003',
  productName: 'LG Washing Machine',
  customer: 'Drake',
  dateCreated: '22-03-2024',
  location: 'Port Harcourt, Nigeria',
  status: 'Cancelled',
 },
 {
  no: '004',
  productName: 'Panasonic Microwave',
  customer: 'Taylor Swift',
  dateCreated: '23-03-2024',
  location: 'Kano, Nigeria',
  status: 'Delivered',
 },
 {
  no: '005',
  productName: 'Sony TV',
  customer: 'Ed Sheeran',
  dateCreated: '24-03-2024',
  location: 'Ibadan, Nigeria',
  status: 'Ongoing',
 },
 {
  no: '006',
  productName: 'Hisense AC',
  customer: 'Rihanna',
  dateCreated: '25-03-2024',
  location: 'Lagos, Nigeria',
  status: 'Delivered',
 },
 {
  no: '007',
  productName: 'HP Laptop',
  customer: 'Chris Brown',
  dateCreated: '26-03-2024',
  location: 'Enugu, Nigeria',
  status: 'Cancelled',
 },
 {
  no: '008',
  productName: 'Apple iPhone',
  customer: 'Selena Gomez',
  dateCreated: '27-03-2024',
  location: 'Benin, Nigeria',
  status: 'Ongoing',
 },
];

export const usersData = [
 {
  no: '001',
  fullName: 'Temitope Williams',
  phoneNumber: '08164626619',
  emailAddress: 'temitopedml@gmail.com',
  status: 'Enabled',
 },
 {
  no: '002',
  fullName: 'Michael Johnson',
  phoneNumber: '08123456789',
  emailAddress: 'michaelj@gmail.com',
  status: 'Enabled',
 },
 {
  no: '003',
  fullName: 'Aisha Bello',
  phoneNumber: '09098765432',
  emailAddress: 'aishabello@yahoo.com',
  status: 'Disabled',
 },
 {
  no: '004',
  fullName: 'David Okoro',
  phoneNumber: '08122334455',
  emailAddress: 'davidokoro@gmail.com',
  status: 'Enabled',
 },
 {
  no: '005',
  fullName: 'Grace Adeyemi',
  phoneNumber: '07055667788',
  emailAddress: 'graceadeyemi@hotmail.com',
  status: 'Enabled',
 },
 {
  no: '006',
  fullName: 'Emeka Chukwu',
  phoneNumber: '08033445566',
  emailAddress: 'emekachukwu@gmail.com',
  status: 'Disabled',
 },
 {
  no: '007',
  fullName: 'Sophia Williams',
  phoneNumber: '08188990077',
  emailAddress: 'sophiawilliams@gmail.com',
  status: 'Enabled',
 },
 {
  no: '008',
  fullName: 'Tunde Balogun',
  phoneNumber: '09011223344',
  emailAddress: 'tundebalogun@yahoo.com',
  status: 'Enabled',
 },
];
